### ISSUE TITLE
requirement.txt 無法安裝

### ISSUE THREAD

**Issue by codax0421** [Bosh-Kuo/Database-2022-Fall#5]
# Context
 pip install -r requirements.txt 無法安裝套件
![image](https://user-images.githubusercontent.com/59133030/206428912-8fe16a76-097c-4b11-9d88-03daf3a88c07.png)

ERROR: Invalid requirement: 'asgiref=3.5.2=pyhd8ed1ab_0' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

好像是conda生出來的requiremnet.txt無法使用。

**Comment by codax0421** [comment]
我試了加多一個“=”但是還是不行
![image](https://user-images.githubusercontent.com/59133030/206429368-ddb0d7ab-8efb-4d04-91b8-773558239118.png)

**Comment by Bosh-Kuo** [comment]
哇 那不要用 conda 好了，我處理一下

**Comment by Bosh-Kuo** [comment]
@codax0421 可以切到 issue-5 這個 branch 幫我確認看看這個 requirement.txt 可不可以用嗎？

**Comment by codax0421** [comment]
> @codax0421 可以切到 issue-5 這個 branch 幫我確認看看這個 requirement.txt 可不可以用嗎？

好，等下試試

**Comment by codax0421** [comment]
已解決
