### ISSUE TITLE
沒Product Id 

### ISSUE THREAD

**Issue by codax0421** [Bosh-Kuo/Database-2022-Fall#8]
# Context
想請問Product id 是不是忘了加在model 上面，query需要用到找特定的product

**Comment by Bosh-Kuo** [comment]
django model 會自動加入 id
在資料庫裡面也可以看到有 id 這欄
可以用 python manage.py shell_plus 在 shell 操作（shell_plus 會把該 import 的套件自動 import shell 則要自己 import ）
<img width="776" alt="截圖 2022-12-10 上午12 59 04" src="https://user-images.githubusercontent.com/79684268/206753572-75f5a2bd-d9f4-44a3-8291-e608502f0933.png">

**Comment by codax0421** [comment]
了解，謝謝
